/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiDirectoryCollection {
        /**
          * Horizontal alignment for scrolling into view.
          * @type {ScrollIntoViewOptions['inline']}
          * @default 'center'
         */
        "alignX": ScrollIntoViewOptions['inline'];
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "align-x"?: ScrollIntoViewOptions['inline'];
        /**
          * Vertical alignment for scrolling into view.
          * @type {ScrollIntoViewOptions['block']}
          * @default 'center'
         */
        "alignY": ScrollIntoViewOptions['block'];
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "align-y"?: ScrollIntoViewOptions['block'];
    }
    interface UiDirectorySegment {
        /**
          * Activates the segment by setting the `active` property to true.
          * @returns
         */
        "activate": () => Promise<void>;
        /**
          * Deactivates the segment by setting the `active` property to false.
          * @returns
         */
        "deactivate": () => Promise<void>;
        /**
          * A unique identifier for the segment.
          * @type {string}
         */
        "mark": string;
    }
}
declare global {
    interface HTMLUiDirectoryCollectionElement extends Components.UiDirectoryCollection, HTMLStencilElement {
    }
    var HTMLUiDirectoryCollectionElement: {
        prototype: HTMLUiDirectoryCollectionElement;
        new (): HTMLUiDirectoryCollectionElement;
    };
    interface HTMLUiDirectorySegmentElement extends Components.UiDirectorySegment, HTMLStencilElement {
    }
    var HTMLUiDirectorySegmentElement: {
        prototype: HTMLUiDirectorySegmentElement;
        new (): HTMLUiDirectorySegmentElement;
    };
    interface HTMLElementTagNameMap {
        "ui-directory-collection": HTMLUiDirectoryCollectionElement;
        "ui-directory-segment": HTMLUiDirectorySegmentElement;
    }
}
declare namespace LocalJSX {
    interface UiDirectoryCollection {
        /**
          * Horizontal alignment for scrolling into view.
          * @type {ScrollIntoViewOptions['inline']}
          * @default 'center'
         */
        "alignX"?: ScrollIntoViewOptions['inline'];
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "align-x"?: ScrollIntoViewOptions['inline'];
        /**
          * Vertical alignment for scrolling into view.
          * @type {ScrollIntoViewOptions['block']}
          * @default 'center'
         */
        "alignY"?: ScrollIntoViewOptions['block'];
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "align-y"?: ScrollIntoViewOptions['block'];
    }
    interface UiDirectorySegment {
        /**
          * A unique identifier for the segment.
          * @type {string}
         */
        "mark": string;
    }
    interface IntrinsicElements {
        "ui-directory-collection": UiDirectoryCollection;
        "ui-directory-segment": UiDirectorySegment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-directory-collection": LocalJSX.UiDirectoryCollection & JSXBase.HTMLAttributes<HTMLUiDirectoryCollectionElement>;
            "ui-directory-segment": LocalJSX.UiDirectorySegment & JSXBase.HTMLAttributes<HTMLUiDirectorySegmentElement>;
        }
    }
}
