/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiDirectoryCollection {
    }
    interface UiDirectorySegment {
    }
}
declare global {
    interface HTMLUiDirectoryCollectionElement extends Components.UiDirectoryCollection, HTMLStencilElement {
    }
    var HTMLUiDirectoryCollectionElement: {
        prototype: HTMLUiDirectoryCollectionElement;
        new (): HTMLUiDirectoryCollectionElement;
    };
    interface HTMLUiDirectorySegmentElement extends Components.UiDirectorySegment, HTMLStencilElement {
    }
    var HTMLUiDirectorySegmentElement: {
        prototype: HTMLUiDirectorySegmentElement;
        new (): HTMLUiDirectorySegmentElement;
    };
    interface HTMLElementTagNameMap {
        "ui-directory-collection": HTMLUiDirectoryCollectionElement;
        "ui-directory-segment": HTMLUiDirectorySegmentElement;
    }
}
declare namespace LocalJSX {
    interface UiDirectoryCollection {
    }
    interface UiDirectorySegment {
    }
    interface IntrinsicElements {
        "ui-directory-collection": UiDirectoryCollection;
        "ui-directory-segment": UiDirectorySegment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-directory-collection": LocalJSX.UiDirectoryCollection & JSXBase.HTMLAttributes<HTMLUiDirectoryCollectionElement>;
            "ui-directory-segment": LocalJSX.UiDirectorySegment & JSXBase.HTMLAttributes<HTMLUiDirectorySegmentElement>;
        }
    }
}
